import { Product } from './types';

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Classic Linen Shirt',
    description: 'A timeless linen shirt perfect for warm weather. Crafted from premium European flax with a relaxed fit that gets better with every wash.',
    price: 89.00,
    originalPrice: 129.00,
    images: [],
    category: 'tops',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Navy', 'Sage', 'Stone'],
    tags: ['new', 'summer', 'essentials'],
    featured: true,
    inStock: true,
    stock: 100,
    rating: 4.8,
    reviews: 124,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now(),
  },
  {
    id: '2',
    name: 'Tailored Wool Blazer',
    description: 'Sharp, single-breasted blazer in pure virgin wool. A wardrobe essential that transitions effortlessly from desk to dinner.',
    price: 295.00,
    images: [],
    category: 'outerwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Charcoal', 'Black', 'Navy'],
    tags: ['featured', 'formal'],
    featured: true,
    inStock: true,
    stock: 75,
    rating: 4.9,
    reviews: 87,
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now(),
  },
  {
    id: '3',
    name: 'Relaxed Denim Jeans',
    description: 'Mid-rise, straight-leg jeans in heavyweight Japanese denim. Vintage-inspired with a modern, comfortable fit.',
    price: 145.00,
    images: [],
    category: 'bottoms',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Indigo', 'Black', 'Light Wash'],
    tags: ['essentials', 'bestseller'],
    featured: true,
    inStock: true,
    stock: 150,
    rating: 4.7,
    reviews: 203,
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now(),
  },
  {
    id: '4',
    name: 'Silk Midi Dress',
    description: 'Effortlessly elegant midi dress in fluid silk charmeuse. Features a draped neckline and gentle A-line silhouette.',
    price: 235.00,
    originalPrice: 320.00,
    images: [],
    category: 'dresses',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Burgundy', 'Black', 'Emerald', 'Blush'],
    tags: ['sale', 'evening'],
    featured: true,
    inStock: true,
    stock: 40,
    rating: 4.6,
    reviews: 56,
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now(),
  },
  {
    id: '5',
    name: 'Cashmere Crew Sweater',
    description: 'Ultra-soft cashmere crewneck sweater. Lightweight yet warm, perfect for layering or wearing on its own.',
    price: 195.00,
    images: [],
    category: 'tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Camel', 'Heather Grey', 'Black', 'Cream'],
    tags: ['winter', 'luxury'],
    featured: true,
    inStock: true,
    stock: 60,
    rating: 4.9,
    reviews: 168,
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now(),
  },
  {
    id: '6',
    name: 'Leather Crossbody Bag',
    description: 'Sleek crossbody bag in full-grain leather. Compact interior fits all essentials with an adjustable strap.',
    price: 175.00,
    images: [],
    category: 'accessories',
    sizes: ['One Size'],
    colors: ['Black', 'Tan', 'Burgundy'],
    tags: ['accessories', 'bestseller'],
    featured: true,
    inStock: true,
    stock: 85,
    rating: 4.7,
    reviews: 92,
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now(),
  },
  {
    id: '7',
    name: 'Organic Cotton Tee',
    description: 'The perfect everyday tee made from 100% organic cotton. Clean seams, no tags, just pure comfort.',
    price: 45.00,
    images: [],
    category: 'tops',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Heather Grey', 'Olive', 'Burgundy', 'Navy'],
    tags: ['essentials', 'sustainable'],
    featured: false,
    inStock: true,
    stock: 200,
    rating: 4.5,
    reviews: 341,
    createdAt: Date.now() - 86400000 * 15,
    updatedAt: Date.now(),
  },
  {
    id: '8',
    name: 'Pleated Wide-Leg Pants',
    description: 'High-waisted, wide-leg trousers with sharp pleats. Flowing fabric creates a beautiful silhouette.',
    price: 165.00,
    images: [],
    category: 'bottoms',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Cream', 'Olive'],
    tags: ['new', 'workwear'],
    featured: false,
    inStock: true,
    stock: 55,
    rating: 4.6,
    reviews: 73,
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now(),
  },
  {
    id: '9',
    name: 'Oversized Denim Jacket',
    description: 'A relaxed take on the classic trucker jacket. Distressed details and a lived-in feel from day one.',
    price: 185.00,
    originalPrice: 220.00,
    images: [],
    category: 'outerwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Light Wash', 'Indigo', 'Black'],
    tags: ['sale', 'trending'],
    featured: false,
    inStock: true,
    stock: 35,
    rating: 4.4,
    reviews: 45,
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now(),
  },
  {
    id: '10',
    name: 'Gold Hoop Earrings',
    description: 'Classic 14k gold-filled hoop earrings. Lightweight, comfortable, and endlessly wearable.',
    price: 68.00,
    images: [],
    category: 'accessories',
    sizes: ['One Size'],
    colors: ['Gold', 'Silver'],
    tags: ['accessories', 'everyday'],
    featured: false,
    inStock: true,
    stock: 120,
    rating: 4.8,
    reviews: 214,
    createdAt: Date.now() - 86400000 * 20,
    updatedAt: Date.now(),
  },
  {
    id: '11',
    name: 'Striped Linen Dress',
    description: 'Breezy linen dress with vertical stripes. Buttom-front with a collared neckline and bracelet sleeves.',
    price: 128.00,
    images: [],
    category: 'dresses',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Blue/White', 'Pink/White', 'Black/White'],
    tags: ['summer', 'vacation'],
    featured: false,
    inStock: true,
    stock: 25,
    rating: 4.3,
    reviews: 38,
    createdAt: Date.now() - 86400000 * 12,
    updatedAt: Date.now(),
  },
  {
    id: '12',
    name: 'Wool Beanie',
    description: 'Ribbed knit beanie in superfine merino wool. Keeps you warm without the itch.',
    price: 42.00,
    images: [],
    category: 'accessories',
    sizes: ['One Size'],
    colors: ['Black', 'Charcoal', 'Cream', 'Burgundy', 'Navy'],
    tags: ['winter', 'essentials'],
    featured: false,
    inStock: true,
    stock: 90,
    rating: 4.6,
    reviews: 156,
    createdAt: Date.now() - 86400000 * 30,
    updatedAt: Date.now(),
  },
];
